.TH ACIDWARP 6 "December 2000"
.SH NAME
acidwarp \- Colour cycling eye\-candy
.SH SYNOPSIS
.B acidwarp
[
.B options
] 
.SH DESCRIPTION
Acidwarp is an eye candy program For more information go to
http://www.noah.org/acidwarp/
.SH COMMAND\-LINE OPTIONS
No options are necessary. Just type 
.B acidwarp
and watch the show. However, you can give the following arguments at the command-line:
.TP 
.B -d --delay seconds
Specifies the number of seconds to delay each picture.  Defaults to 20.
.TP 
.B -h --help
Prints a help screen.
.TP 
.B -n --nologo
Tells acidwarp not to display the logo at starup.
.TP 
.B -s --speed microseconds
Specifies the speed of the palette rotation. Defaults to 25000.
.TP 
.B -w --warper
Prints a text file explaining how to build "The Warper".
.SH KEYBOARD COMMANDS
When acidwarp is running you can control it with keyboard commands.
.TP
.B Up
causes the pallette to rotate faster.
.TP
.B Down
causes the pallette to rotate slower.
.TP
.B l
(L)ock on the current pattern.
.TP
.B k
switch to the next pallette.
.TP
.B p
(P)ause. Totally stops pallette rotation and pattern changing.
.TP
.B q
(Q)uit. Causes Acidwarp to exit.
.TP
.B n 
(N)ext pattern.
.SH AUTHORS
The authors of the MS\-DOS version of 
.B acidwarp 
are Noah Spurrier (noah@noah.org) and Mark Bilk.  
.PP
The Linux port was done by Steven Wills (willssl@jmu.edu).
.PP
The SDL port was done by Boris Gjenero (boris.gjenero@gmail.com).
.PP
This man page was written by Michael Sterrett (msterret@css.tayloru.edu) and updated by Boris Gjenero.
.SH COPYRIGHT
Copyright (C) 1992, 1993 Noah Spurrier and Mark Bilk.

.B acidwarp 
is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License.


